FROM python:3.8-slim-buster

WORKDIR /app

COPY requirements-tests.txt /app/requirements-tests.txt
RUN pip3 install --no-cache-dir -r requirements-tests.txt

RUN mkdir model
RUN curl -L https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english/resolve/main/pytorch_model.bin -o ./model/pytorch_model.bin
RUN curl https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english/resolve/main/config.json -o ./model/config.json
RUN curl https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english/resolve/main/tokenizer.json -o ./model/tokenizer.json
RUN curl https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english/resolve/main/tokenizer_config.json -o ./model/tokenizer_config.json
RUN curl https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english/resolve/main/vocab.txt -o ./model/vocab.txt


COPY setup.py /app/setup.py
RUN pip install .

COPY . .

EXPOSE 8000

ENTRYPOINT ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "project.app:app"]