org: dudeperf3ct
app: serverless-fastapi-aws-lambda-deploy
service: sentiment-api

frameworkVersion: "2 || 3"

provider:
  name: aws
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images:
      sentimentapp:
        path: ./

functions:
  hello:
    image:
      name: sentimentapp
    events:
      - http:
          path: /{proxy+}
          method: ANY
